route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "telegram"

receivers:
  - name: "telegram"
    telegram_configs:
      - api_url: "https://api.telegram.org"
        bot_token: "SEU_BOT_TOKEN_AQUI"
        chat_id: SEU_CHAT_ID_AQUI
        parse_mode: "HTML"
        message: |
          🚨 <b>{{ .GroupLabels.alertname }}</b>
          {{ range .Alerts }}
          <b>Alerta:</b> {{ .Annotations.summary }}
          {{ .Annotations.description }}
          <b>Severidade:</b> {{ .Labels.severity }}
          {{ end }}