# whitelist.example.ps1 - modelo de whitelist de processos
# COPIE para whitelist.ps1 e adapte a sua maquina (o whitelist.ps1 real
# NAO e versionado: e o inventario pessoal de software de quem roda o canario).
# Nomes SEM .exe (o coletor normaliza p/ minusculas).

$KnownProcesses = @(
    'svchost',
    'system',
    'lsass',
    'services',
    'wininit',
    'winlogon',
    'explorer',
    'dwm',
    'msmpeng',
    'securityhealthservice',
    'mpdefendercoreservice',
    'searchindexer',
    'searchhost',
    'spoolsv',
    'runtimebroker',
    'smartscreen',
    'startmenuexperiencehost',
    'systemsettings',
    'applicationframehost',
    'onedrive',
    'microsoftedgeupdate',
    'm365copilot',
    'chrome',
    'msedge',
    'firefox',
    'brave',
    'code',
    'node',
    'python',
    'git',
    'curl',
    'powershell',
    'pwsh',
    'docker',
    'dockerd',
    'docker-proxy',
    'com.docker.backend',
    'docker-agent',
    'wslhost',
    'vmmem',
    'avp',
    'ksde'
)
